### ISSUE TITLE
Implement the component

### ISSUE THREAD

**Issue by mdpiper** [csdms/bmi-geotiff#2]
I'd like to make the planning and development of this project as open and as public as possible. GitHub provides a good place for this.

Project planning is described in #1. This is a record of what I actually did.

## Tasks

- [x] Create GitHub repository ([csdms/bmi-geotiff](https://github.com/csdms/bmi-geotiff)) with README and license
- [x] Make directories: bmi_geotiff, tests, examples, docs
- [x] Collect build files (copy from [bmi-topography](https://github.com/csdms/bmi-topography) and tailor, using [PyPA guidelines](https://packaging.python.org/))
  * pyproject.toml 
  * setup.cfg (include flake8 and zest.releaser config because they don't yet work in pyproject.toml)
  * Makefile
  * environment.yaml
  * autogenerate a setup.py file through my Makefile
- [x] Set up package definition file and iteratively write library (io.py) and tests (test_io.py)
  * `make test`
  * `make pretty`
- [x] Make example for library
- [x] BMI the library (bmi.py)
  * generate skeleton with `bmipy-render`
  * fill in the methods of BmiGeoTiff
  * make a config file (place in examples and link in tests/data)
  * test iteratively with *bmi-tester* (`make bmi-test`)
- [x] Make example for BMI
- [x] Add content to README
  * overview -- uses experimental `xarray.open_rasterio`
  * install instructions
  * example(s)
  * acknowledgment
- [x] Add package metadata files (copy from bmi-topography and modify)
  * CHANGES.md
  * CONTRIBUTING.md
  * use [setuptools-scm](https://github.com/pypa/setuptools_scm/) to include files in the sdist instead of using a MANIFEST.in file
- [x] Generate distribution archives (`make build`)
    * check content in the dist directory
    * test upload to test.pypi.org (`make testpypi`)
- [x] Create v0.1 release with zest.releaser (`make fullrelease`)
    * upload to PyPI
- [x] Write documentation
  * run `sphinx-quickstart` from the docs directory
  * include README
  * build API docs
  * automate versioning for docs
  * deploy to Read the Docs
    * use .readthedocs.yaml
- [x] Format and lint (`make pretty` and `make lint`)
- [x] CI with GitHub Actions
  * build and test
  * format
  * lint
  * build docs
- [x] Create v0.2 release and upload to PyPI
- [x] Make a conda-forge package
  * use PyPI for source tarball instead of GitHub
- [x] Add a DOI through Zenodo
   * turn repo "on" in Zenodo
   * make a release from a tag on GitHub
   * edit title and license on Zenodo
   * make a CITATION document
- [x] Babelize
- [x] Make a pymt package (*pymt_geotiff*)
  * add component metadata
  * include script and notebook examples
  * create brief documentation (including notebook)
  * deploy docs to Read the Docs (use .readthedocs.yaml)
  * make a conda-forge package
- [x] Add to CSDMS Model Repository (this will populate Data Components page)

**Comment by mdpiper** [comment]
It's tricky to get the crs using *get_value*:
```
>>> var_name = "coordinate_reference_system__string"
>>> nbytes = bmi.get_var_nbytes(var_name)
>>> dest = np.ndarray((1,), dtype="U{}".format(nbytes))
>>> r = bmi.get_value(var_name, dest)

>>> print(r)
['+init=epsg:32618']

>>> print(dest)
['+init=epsg:32618']
```

**Comment by mdpiper** [comment]
`matplotlib,pyplot.imshow` can display an RGB image, but it needs band sequential ordering:
```python
rasterBSQ = np.transpose(rasterRGB, axes=[1, 2, 0])
plt.imshow(rasterBSQ)
```

**Comment by mdpiper** [comment]
I'm using setuptools-scm to include repository files outside the package, like Makefile, CHANGES.md, etc. It conflicts slightly with zest.releaser, which shows a dirty repository when running `fullrelease`:
```
INFO: Starting release.
Tag needed to proceed, you can use the following command:
git tag v0.2.dev5+ged6292c -m 'Tagging 0.2.dev5+ged6292c'
Run this command (Y/n)? n
```
The workaround is to tag the repo before running `fullrelease`:
```
$ git tag v0.2 -m 'Tagging 0.2'
```

**Comment by mdpiper** [comment]
Release text (using v0.2 tag):

## CSDMS GeoTIFF data component

The public release of the GeoTIFF data component, with examples, CI, docs, and installation through `pip` and `conda`.
